### ISSUE TITLE
syntax error when making atomizer from cloned repo

### ISSUE THREAD

**Issue by ryants** [RuleWorld/atomizer#1]
When I run "make" in the top directory I get the following error:
```
1993 ERROR: invalid syntax (async.py, line 16)
Traceback (most recent call last):
  File "/auto/nest/nest/u/ryants/tools/atomizer/pyinstaller2/PyInstaller/depend/owner.py", line 110, in getmod
    co = compile(stuff.replace("\r\n", "\n"), py[0], 'exec')
  File "async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax
make: *** [all] Error 10
```
I am using Ubuntu 12.04 LTS if that helps troubleshoot at all

**Comment by jjtapia** [comment]
Hello,

The error is because of some changes they did in one of the atomizer's dependencies that makes it incompatible with Python 2.7, pexpect in particular.You can check the requirements.txt for the particular version of pexpect atomizer needs.

If you already have pexpect installed you can do

$ pip uninstall pexpect
$ pip install pexpect=3.3

**Comment by ryants** [comment]
Thanks for the tip.  If I switch to Python 3.x will that prevent me from having to downgrade pexpect?

**Comment by jjtapia** [comment]
Atomizer is not Python 3 compatible as of this moment. An alternative solution would be to upgrade the version of pip so that it can deal with the non compatible elements in the package (as reported [here](https://github.com/pexpect/pexpect/issues/290)) however I haven't tested this solution myself.

**Comment by jjtapia** [comment]
This error was addressed by installing the dependencies in a Python virtualenv
